#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2018 Aleksandr V. Piskunov <aleksandr.v.piskunov@gmail.com>.
# Copyright (C) 2015-2018 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
#
# This watchdog script tries to re-resolve hostnames for inactive WireGuard peers.

# shellcheck disable=SC1091,SC3043

. /lib/functions.sh

check_peer_activity() {
	local cfg="$1" iface="$2" disabled public_key endpoint_host endpoint_port
	local persistent_keepalive last_handshake idle_seconds IPV4 IPV6
	local IPV4_REGEX="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}"
	local IPV6_REGEX="\(\([0-9A-Fa-f]\{1,4\}:\)\{1,\}\)\(\([0-9A-Fa-f]\{1,4\}\)\{0,1\}\)\(\(:[0-9A-Fa-f]\{1,4\}\)\{1,\}\)"

	config_get_bool disabled "${cfg}" "disabled" 0
	config_get public_key "${cfg}" "public_key"
	config_get endpoint_host "${cfg}" "endpoint_host"
	config_get endpoint_port "${cfg}" "endpoint_port"
	[ "${disabled}" -eq 1 ] && return 0
	persistent_keepalive="$(awg show "${iface}" persistent-keepalive | grep "${public_key}" | awk '{print $2}')"
	[ -z "${endpoint_host}" ] && return 0
	if [ -z "${persistent_keepalive}" ] || [ "${persistent_keepalive}" = "off" ]; then return 0; fi
	IPV4="$(echo "${endpoint_host}" | grep -m 1 -o "$IPV4_REGEX$")"
	IPV6="$(echo "${endpoint_host}" | grep -m 1 -o "$IPV6_REGEX")"
	[ -n "${IPV4}${IPV6}" ] && return 0
	last_handshake="$(awg show "${iface}" latest-handshakes | grep "${public_key}" | awk '{print $2}')"
	[ -z "${last_handshake}" ] && return 0
	idle_seconds=$(($(date +%s) - last_handshake))
	[ "${idle_seconds}" -lt 150 ] && return 0
	logger -t "amneziawg_monitor" "${iface} endpoint ${endpoint_host}:${endpoint_port} is not responding for ${idle_seconds} seconds, trying to re-resolve hostname"
	awg set "${iface}" peer "${public_key}" endpoint "${endpoint_host}:${endpoint_port}"
}

wg_ifaces="$(ubus -S call network.interface dump | jsonfilter -e '@.interface[@.up=true]' | jsonfilter -a -e '@[@.proto="amneziawg"].interface' | tr "\n" " ")"
config_load network
for iface in $wg_ifaces; do
	config_foreach check_peer_activity "amneziawg_${iface}" "${iface}"
done
